python main.py\
	--mode meta-test\
    --num_inner_tasks 3\
    --layer_size 64\
	--seed 42\
	--num_episodes 4000\
	--meta_train_devices 'galaxy_s10_cpu_head,galaxy_s10_gpu_head,galaxy_s22_nnapi_head'\
	--meta_valid_devices 'galaxy_s22_cpu_head,galaxy_s22_gpu_head'\
	--meta_test_devices 'galaxy_s10_nnapi_head'\
	--use_wandb true